modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="bringearthslabsback"
version="0.0.1"
displayName="BringEarthSlabsBack!"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Nacroni, MCreator"
description="Brings Dirt and Grass slabs back. Made with MCreator."

[[dependencies.bringearthslabsback]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




